/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiHbStopRouteImport } from './routes/api/hb-stop'
import { Route as AuthenticatedIpRouteImport } from './routes/_authenticated/ip'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedEmailHeadersRouteImport } from './routes/_authenticated/email-headers'
import { Route as AuthenticatedCyberchefRouteImport } from './routes/_authenticated/cyberchef'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHbStopRoute = ApiHbStopRouteImport.update({
  id: '/api/hb-stop',
  path: '/api/hb-stop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIpRoute = AuthenticatedIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailHeadersRoute =
  AuthenticatedEmailHeadersRouteImport.update({
    id: '/email-headers',
    path: '/email-headers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCyberchefRoute = AuthenticatedCyberchefRouteImport.update({
  id: '/cyberchef',
  path: '/cyberchef',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cyberchef': typeof AuthenticatedCyberchefRoute
  '/email-headers': typeof AuthenticatedEmailHeadersRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/ip': typeof AuthenticatedIpRoute
  '/api/hb-stop': typeof ApiHbStopRoute
  '/api/proxy': typeof ApiProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cyberchef': typeof AuthenticatedCyberchefRoute
  '/email-headers': typeof AuthenticatedEmailHeadersRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/ip': typeof AuthenticatedIpRoute
  '/api/hb-stop': typeof ApiHbStopRoute
  '/api/proxy': typeof ApiProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cyberchef': typeof AuthenticatedCyberchefRoute
  '/_authenticated/email-headers': typeof AuthenticatedEmailHeadersRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/ip': typeof AuthenticatedIpRoute
  '/api/hb-stop': typeof ApiHbStopRoute
  '/api/proxy': typeof ApiProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/cyberchef'
    | '/email-headers'
    | '/history'
    | '/ip'
    | '/api/hb-stop'
    | '/api/proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/cyberchef'
    | '/email-headers'
    | '/history'
    | '/ip'
    | '/api/hb-stop'
    | '/api/proxy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/cyberchef'
    | '/_authenticated/email-headers'
    | '/_authenticated/history'
    | '/_authenticated/ip'
    | '/api/hb-stop'
    | '/api/proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHbStopRoute: typeof ApiHbStopRoute
  ApiProxyRoute: typeof ApiProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hb-stop': {
      id: '/api/hb-stop'
      path: '/api/hb-stop'
      fullPath: '/api/hb-stop'
      preLoaderRoute: typeof ApiHbStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ip': {
      id: '/_authenticated/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof AuthenticatedIpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-headers': {
      id: '/_authenticated/email-headers'
      path: '/email-headers'
      fullPath: '/email-headers'
      preLoaderRoute: typeof AuthenticatedEmailHeadersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cyberchef': {
      id: '/_authenticated/cyberchef'
      path: '/cyberchef'
      fullPath: '/cyberchef'
      preLoaderRoute: typeof AuthenticatedCyberchefRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCyberchefRoute: typeof AuthenticatedCyberchefRoute
  AuthenticatedEmailHeadersRoute: typeof AuthenticatedEmailHeadersRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedIpRoute: typeof AuthenticatedIpRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCyberchefRoute: AuthenticatedCyberchefRoute,
  AuthenticatedEmailHeadersRoute: AuthenticatedEmailHeadersRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIpRoute: AuthenticatedIpRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHbStopRoute: ApiHbStopRoute,
  ApiProxyRoute: ApiProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
