/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiHbStopRouteImport } from './routes/api/hb-stop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHbStopRoute = ApiHbStopRouteImport.update({
  id: '/api/hb-stop',
  path: '/api/hb-stop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/hb-stop': typeof ApiHbStopRoute
  '/api/proxy': typeof ApiProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/hb-stop': typeof ApiHbStopRoute
  '/api/proxy': typeof ApiProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/hb-stop': typeof ApiHbStopRoute
  '/api/proxy': typeof ApiProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/hb-stop' | '/api/proxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/hb-stop' | '/api/proxy'
  id: '__root__' | '/' | '/api/hb-stop' | '/api/proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHbStopRoute: typeof ApiHbStopRoute
  ApiProxyRoute: typeof ApiProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hb-stop': {
      id: '/api/hb-stop'
      path: '/api/hb-stop'
      fullPath: '/api/hb-stop'
      preLoaderRoute: typeof ApiHbStopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHbStopRoute: ApiHbStopRoute,
  ApiProxyRoute: ApiProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
